-- Create accommodations table
create table public.accommodations (
  id bigint generated by default as identity primary key,
  name text,
  category text,
  rating float,
  reviews int,
  price int,
  price_unit text,
  description text,
  address text,
  phone text,
  website text,
  position float8[],
  images text[],
  amenities text[],
  max_guests int,
  check_in_time text,
  check_out_time text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.accommodations enable row level security;

-- Create policy to allow public read access
create policy "Allow public read access"
  on public.accommodations
  for select
  to public
  using (true);

-- Insert seed data
insert into public.accommodations (
  name, category, rating, reviews, price, price_unit, description, address, phone, website, position, images, amenities, max_guests, check_in_time, check_out_time
) values
(
  'Lakefie Lodge',
  'Premium Lodge',
  4.9,
  87,
  2850,
  'per night',
  'Luxury lakeside lodge with stunning mountain views and world-class amenities. Perfect for romantic getaways.',
  '123 Riverside Rd, Dullstroom',
  '+27 13 456 7890',
  'lakeflelodge.co.za',
  '{-25.41935, 30.08856}',
  ARRAY['https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop', 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=300&fit=crop', 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=400&h=300&fit=crop'],
  ARRAY['Free WiFi', 'Breakfast Included', 'Lake View', 'Fireplace', 'Spa'],
  4,
  '15:00',
  '11:00'
),
(
  'Mountain View Cottage',
  'Cozy Cottage',
  4.7,
  124,
  1650,
  'per night',
  'Charming cottage nestled in the mountains with breathtaking views and modern comforts.',
  '45 Highland Road, Dullstroom',
  '+27 13 456 7891',
  'mountaincottage.co.za',
  '{-25.42156, 30.10892}',
  ARRAY['https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=400&h=300&fit=crop', 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=400&h=300&fit=crop'],
  ARRAY['Free WiFi', 'Garden View', 'BBQ Area', 'Pet Friendly'],
  6,
  '14:00',
  '10:00'
),
(
  'Riverside Retreat',
  'Boutique Hotel',
  4.8,
  95,
  2200,
  'per night',
  'Elegant riverside accommodation with luxury amenities and exceptional service.',
  '78 River Lane, Dullstroom',
  '+27 13 456 7892',
  'riversideretreat.co.za',
  '{-25.41789, 30.10234}',
  ARRAY['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=400&h=300&fit=crop', 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=400&h=300&fit=crop'],
  ARRAY['Free WiFi', 'Restaurant', 'Room Service', 'Conference Facilities'],
  2,
  '15:00',
  '12:00'
);
